### PR TITLE
added uri and jdbc uri in credentials

### PR DESCRIPTION
**Pull request by xiujiao**
The `uri` and `jdbc_uri` is added according to this doc 
https://docs.pivotal.io/partners/crunchy/using.html#service-credentials

`hostname` is added to support OCF format according to this doc 
https://docs.cloudfoundry.org/services/binding-credentials.html

### CODE REVIEW

**Comment by jhunt** [comment]
Should we add the rest of the credentials fields, like `read_uri`?

**Comment by xiujiao** [comment]
> Should we add the rest of the credentials fields, like `read_uri`?

I was debating for a couple of reasons: 1) for standalone postgres, the read_uri is the same with uri, right? then the app should not have cared about `read_uri` ; 2) for cluster one, how I can know which is read_host , does read_host become master when master is down? (not db expert yet 😄 
We could add those entries, just they may not be set as they are named, like read_uri, is not read only etc

**Comment by jhunt** [comment]
I would go ahead and add them.  The read_uri is there for applications that know they can do read-only queries in a replicated setup.  If the postgres isn't clustered, the read_uri is the same as the write_uri.

**Comment by xiujiao** [comment]
@jhunt I added read_uri and other fields, tested in our lab. Could you please take one more look and merge it? Thx

**Pull request merged**
